### ISSUE TITLE
Missing affiliations for authors with multiple ones from different papers

### ISSUE THREAD

**Issue by marblestation** [adsabs/author_affiliation_service#17]
To reproduce:

1. Go to qa
2. Search author:"^blanco-cuaresma, s."
3. Only the affiliations from Bordeaux and Geneva appear, not CfA.

In the list of articles there is some where CfA affiliation is the second one and others where it is the first and only one, but it does not appear in the export.

**Comment by golnazads** [comment]
Not all affiliations are filled in solr. Sergi I checked your publications,
and they are mostly '-' for affiliation.

**Comment by aaccomazzi** [comment]
Another specific example: select the paper 2017ewas.confE...8B and then ask for the author-affiliation form.  The request returns an error message.  In general, I suspect that when requesting the form for N records the service is not successfully incorporating results for a subset, as can be seen by some affiliations not being present in the final list.

A separate UI issue that appears with a failure is the fact that BBB seems to display the previous data retrieved by the service (in this case the data from my previous search for my name).  @thostetler should take a look

![image](https://user-images.githubusercontent.com/910261/36645685-9baf96da-1a3a-11e8-9b19-cf35e38d4b60.png)

**Comment by golnazads** [comment]
on adslabs.org

query for bibcode = 2017ewas.confE...8B, it returns the record.

query for bibcode plus year >=2014 and it does not return anything!
bibcode:2017ewas.confE...8B and year>=2014

The year is right for this record.

Now query for 2015 or 2013 and returns the record, but not for 2014!

That is what is happening here. Since the numyears is set to include the
last four years, the query includes the year>=2014 in the query. Solr does
not return the record. Service returns no data from solr error.


On Sun, Feb 25, 2018 at 2:48 PM, Alberto Accomazzi <notifications@github.com

**Comment by golnazads** [comment]
on adslabs.org query for bibcode = 2017ewas.confE...8B it returns the
record.
query for bibcode plus year >=2014 and it does not return anything!
bibcode:2017ewas.confE...8B and year>=2014
And the year is right for this record. That is what is happening here.
Since the numyears is set to include the last four year, the query includes
the year. The service returns no data from solr error.

On Sun, Feb 25, 2018 at 2:48 PM, Alberto Accomazzi <notifications@github.com

**Comment by aaccomazzi** [comment]
The year cutoff in the solr query is not created correctly, should be: `year:[2014 TO 3000]` (upper limit is arbitrarily high)

**Comment by golnazads** [comment]
thank you so much. I had seen the range query for solr, but somehow got confused. it is fixed now.

**Comment by marblestation** [comment]
Thanks @golnazads !
